"""
LLM providers for the MAO Assistant, and the OpenAI-compatible tool-calling loop.

Gemini keeps its native loop in gemini.py. Groq and NVIDIA NIM both speak OpenAI chat-completions
with tool calling, so they share the client here. Keys travel in the Authorization header only.
"""

import asyncio
import json
import re
from typing import Any, Dict, List, Optional, Tuple

import httpx

from ...config import settings
from .errors import AssistantError, AssistantNotConfigured
from .prompts import build_system_prompt
from .tools import ACTION_TOOLS, TOOL_DECLARATIONS, TOOL_FUNCTIONS, execute_tool, tool_succeeded

PROVIDER_ORDER = ("gemini", "groq", "nvidia")  # master preference, by availability
PROVIDER_LABELS = {"gemini": "Gemini", "groq": "Groq", "nvidia": "NVIDIA NIM"}

MAX_TOOL_ROUNDS = 8
# Tighter than Gemini's: Groq's free tier is 8K tokens/minute for gpt-oss, schemas included.
MAX_TOOL_RESULT_CHARS = 6000
MAX_RETRY_AFTER_SECONDS = 4.0


def new_client() -> httpx.AsyncClient:
    """Client factory for every outbound assistant call; tests swap it for a MockTransport client."""
    return httpx.AsyncClient(timeout=60.0)


def provider_key(provider: str) -> str:
    return getattr(settings, f"{provider.upper()}_API_KEY", "") or ""


def provider_model(provider: str) -> str:
    return getattr(settings, f"{provider.upper()}_MODEL", "") or ""


def is_configured(provider: str) -> bool:
    return provider in PROVIDER_ORDER and bool(provider_key(provider))


def configured_providers() -> List[str]:
    return [p for p in PROVIDER_ORDER if is_configured(p)]


def master_candidates() -> List[str]:
    """Configured providers in master order. ASSISTANT_MASTER_PROVIDER moves one to the front."""
    candidates = configured_providers()
    forced = (settings.ASSISTANT_MASTER_PROVIDER or "").strip().lower()
    if forced in candidates:
        candidates.remove(forced)
        candidates.insert(0, forced)
    return candidates


def select_master() -> Optional[str]:
    candidates = master_candidates()
    return candidates[0] if candidates else None


def not_configured_error() -> AssistantNotConfigured:
    return AssistantNotConfigured(
        "No assistant provider is configured. Set GEMINI_API_KEY, GROQ_API_KEY or NVIDIA_API_KEY in "
        "backend/.env and restart the backend."
    )


# -- OpenAI-compatible chat completions (Groq, NVIDIA NIM) ---------------------------------

def _base_url(provider: str) -> str:
    return (getattr(settings, f"{provider.upper()}_BASE_URL", "") or "").rstrip("/")


def _provider_extras(provider: str, model: str) -> Dict[str, Any]:
    """Both default models are hybrid reasoners; a tool router wants the reasoning short or off."""
    if provider == "groq" and model.startswith("openai/gpt-oss"):
        return {"reasoning_effort": "low"}
    if provider == "nvidia" and "nemotron" in model:
        return {"chat_template_kwargs": {"enable_thinking": False}}
    return {}


def openai_tools() -> List[Dict[str, Any]]:
    return [
        {"type": "function", "function": {
            "name": d["name"],
            "description": d["description"],
            "parameters": d.get("parameters") or {"type": "object", "properties": {}},
        }}
        for d in TOOL_DECLARATIONS
    ]


async def chat_completion(
    client: httpx.AsyncClient,
    provider: str,
    messages: List[Dict[str, Any]],
    tools: Optional[List[Dict[str, Any]]] = None,
    max_tokens: Optional[int] = None,
    temperature: float = 0.3,
) -> Dict[str, Any]:
    """One chat-completions call; returns choices[0].message. Retries once on 429 (short retry-after)
    and on 400, which is how Groq reports a malformed tool call generated by the model."""
    label, model = PROVIDER_LABELS[provider], provider_model(provider)
    body: Dict[str, Any] = {"model": model, "messages": messages, "temperature": temperature,
                            **_provider_extras(provider, model)}
    if tools:
        body.update({"tools": tools, "tool_choice": "auto"})
    if max_tokens:
        body["max_tokens"] = max_tokens

    response = None
    for attempt in range(2):
        try:
            response = await client.post(
                f"{_base_url(provider)}/chat/completions",
                headers={"Authorization": f"Bearer {provider_key(provider)}"},
                json=body,
            )
        except httpx.HTTPError as exc:
            raise AssistantError(f"Could not reach the {label} API: {exc.__class__.__name__}") from exc
        if response.status_code == 200:
            break
        if attempt == 0 and response.status_code == 429:
            try:
                delay = float(response.headers.get("retry-after", "1"))
            except ValueError:
                delay = 1.0
            if delay <= MAX_RETRY_AFTER_SECONDS:
                await asyncio.sleep(delay)
                continue
        if attempt == 0 and response.status_code == 400 and tools:
            continue
        break

    if response.status_code != 200:
        try:
            error = response.json().get("error", "")
            detail = error.get("message", "") if isinstance(error, dict) else str(error)
        except ValueError:
            detail = ""
        raise AssistantError(f"{label} API returned {response.status_code}. {detail}".strip())
    try:
        return response.json()["choices"][0]["message"] or {}
    except (ValueError, KeyError, IndexError, TypeError) as exc:
        raise AssistantError(f"{label} API returned an unexpected response.") from exc


_THINK_BLOCK = re.compile(r"<think>.*?</think>", re.DOTALL | re.IGNORECASE)
_LEAKED_CALL = re.compile(r"<tool_?call>\s*(.*?)\s*</tool_?call>", re.DOTALL | re.IGNORECASE)
# The whole message must be call markup. Markup embedded in prose (e.g. the model quoting a pasted
# record that contains "<tool_call>...") is text, never a call: that would be an injection path.
_ONLY_LEAKED_CALLS = re.compile(r"(?:\s*<tool_?call>.*?</tool_?call>\s*)+", re.DOTALL | re.IGNORECASE)


def clean_text(content: Any) -> str:
    """Visible answer text: reasoning blocks are dropped and never fed back into the history."""
    return _THINK_BLOCK.sub("", content if isinstance(content, str) else "").strip()


def _leaked_call(candidate: Any) -> Optional[Tuple[str, Dict[str, Any]]]:
    if isinstance(candidate, list) and candidate:
        candidate = candidate[0]
    if not isinstance(candidate, dict) or candidate.get("name") not in TOOL_FUNCTIONS:
        return None
    args = candidate.get("arguments", candidate.get("parameters", {}))
    if isinstance(args, str):
        try:
            args = json.loads(args)
        except ValueError:
            return None
    return (candidate["name"], args) if isinstance(args, dict) else None


def parse_tool_calls(message: Dict[str, Any]) -> List[Dict[str, Any]]:
    """
    Tool calls of a model turn as [{id, name, args}]; args is None when the JSON was malformed.
    Nemotron models sometimes print the call markup into `content` instead of `tool_calls`. That is
    honoured only when the ENTIRE content is <tool_call> blocks or one bare JSON call naming a known tool.
    """
    calls = []
    tool_calls = message.get("tool_calls")
    for index, call in enumerate(tool_calls if isinstance(tool_calls, list) else []):
        if not isinstance(call, dict):
            continue  # malformed item from a non-conforming server
        function = call.get("function") if isinstance(call.get("function"), dict) else {}
        raw = function.get("arguments")
        try:
            args = raw if isinstance(raw, dict) else json.loads(raw or "{}")
            args = {} if args is None else args  # "null": how some servers spell "no arguments"
        except (ValueError, TypeError):
            args = None
        calls.append({"id": call.get("id") or f"call_{index}", "name": str(function.get("name") or ""),
                      "args": args if isinstance(args, dict) or args is None else None})
    if calls:
        return calls

    content = clean_text(message.get("content"))
    if _ONLY_LEAKED_CALLS.fullmatch(content):
        blocks = _LEAKED_CALL.findall(content)
    else:
        blocks = [content] if content.startswith(("{", "[")) else []  # json.loads below rejects trailing prose
    for index, block in enumerate(blocks):
        try:
            leaked = _leaked_call(json.loads(block))
        except ValueError:
            continue
        if leaked:
            calls.append({"id": f"call_leaked_{index}", "name": leaked[0], "args": leaked[1]})
    return calls


def _to_openai_messages(messages: List[Dict[str, str]], system: str) -> List[Dict[str, Any]]:
    out: List[Dict[str, Any]] = [{"role": "system", "content": system}]
    for message in messages:
        text = (message.get("content") or "").strip()
        if text:  # no "name" field: Groq rejects it
            out.append({"role": "assistant" if message.get("role") == "assistant" else "user", "content": text})
    return out


async def chat(
    provider: str,
    messages: List[Dict[str, str]],
    focus_patient_id: Optional[str] = None,
    client: Optional[httpx.AsyncClient] = None,
) -> Dict[str, Any]:
    """
    Master loop on an OpenAI-compatible provider. Same contract as gemini.chat:
    returns {"reply", "actions": [{tool, args, is_action, ok}], "model"}.
    """
    if not is_configured(provider) or provider == "gemini":
        raise AssistantNotConfigured(f"{provider.upper()}_API_KEY is not set. Add it to backend/.env and restart the backend.")

    history = _to_openai_messages(messages, build_system_prompt(focus_patient_id))
    if len(history) < 2 or history[-1]["role"] != "user":
        raise AssistantError("The conversation must end with a user message.")

    model = provider_model(provider)
    tools = openai_tools()
    actions: List[Dict[str, Any]] = []
    owns_client = client is None
    client = client or new_client()
    try:
        for _ in range(MAX_TOOL_ROUNDS):
            message = await chat_completion(client, provider, history, tools=tools, temperature=0.3)
            calls = parse_tool_calls(message)

            if not calls:
                reply = clean_text(message.get("content"))
                return {"reply": reply or "I couldn't produce an answer for that (empty response). Try rephrasing.",
                        "actions": actions, "model": model}

            # Re-built rather than echoed: drops reasoning_content and normalizes leaked calls.
            history.append({"role": "assistant", "content": "", "tool_calls": [
                {"id": c["id"], "type": "function",
                 "function": {"name": c["name"], "arguments": json.dumps(c["args"] or {})}}
                for c in calls
            ]})
            for call in calls:
                if call["args"] is None:
                    result: Dict[str, Any] = {"error": f"Arguments for {call['name']} were not valid JSON. Call it again."}
                else:
                    result = await execute_tool(call["name"], call["args"])
                actions.append({
                    "tool": call["name"],
                    "args": call["args"] or {},
                    "is_action": call["name"] in ACTION_TOOLS,
                    "ok": tool_succeeded(result),
                })
                payload = json.dumps(result, default=str)
                if len(payload) > MAX_TOOL_RESULT_CHARS:
                    payload = json.dumps({"truncated": True, "data": payload[:MAX_TOOL_RESULT_CHARS]})
                history.append({"role": "tool", "tool_call_id": call["id"], "content": payload})

        return {
            "reply": "I ran out of tool steps before finishing. Here is what I did so far; ask me to continue.",
            "actions": actions,
            "model": model,
        }
    finally:
        if owns_client:
            await client.aclose()


async def complete(provider: str, client: httpx.AsyncClient, system: str, user: str, max_tokens: int = 600) -> str:
    """One tool-less completion on any provider. Used for the specialists."""
    if provider == "gemini":
        from . import gemini

        return await gemini.complete(client, system, user)
    message = await chat_completion(
        client, provider,
        [{"role": "system", "content": system}, {"role": "user", "content": user}],
        max_tokens=max_tokens,
    )
    return clean_text(message.get("content"))
